### ISSUE TITLE
论如何用屎筑一座山 | Lolico's Blog

### ISSUE THREAD

**Issue by c3b2a7** [c3b2a7/c3b2a7.github.io#20]
https://lolico.me/2020/03/23/How-to-build-a-mountain-with-full-shit/

**Comment by z775729168** [comment]
是性别的属性多余了？还有其他吗，date不应该是数字？也许是怪怪的网课。

**Comment by LOLICOL1** [comment]
> @z775729168
> 是性别的属性多余了？还有其他吗，date不应该是数字？也许是怪怪的网课。

因为说到数据库字段类型的选择，性别用enum类型不太好，就用01来代替，然后生日用datetime或者其他时间类型也不太好，数据库中就存时间戳，然后程序中来格式化，所以类里面就有了属性和属性view这么一个东西...

**Comment by z775729168** [comment]
> @LOLICOL1
> > @z775729168
> > 是性别的属性多余了？还有其他吗，date不应该是数字？也许是怪怪的网课。
> 
> 因为说到数据库字段类型的选择，性别用enum类型不太好，就用01来代替，然后生日用datetime或者其他时间类型也不太好，数据库中就存时间戳，然后程序中来格式化，所以类里面就有了属性和属性view这么一个东西...

关于时间随便看了一篇文章：https://www.vertabelo.com/blog/what-datatype-should-you-use-to-represent-time-in-mysql-we-compare-datetime-timestamp-and-int/
不好说，还是要看做什么用，还有人的生日等。也许不是那么怪的网课😀

**Comment by LOLICOL1** [comment]
> @z775729168
> 
> 
> > @LOLICOL1
> > > @z775729168
> > > 是性别的属性多余了？还有其他吗，date不应该是数字？也许是怪怪的网课。
> > 
> > 因为说到数据库字段类型的选择，性别用enum类型不太好，就用01来代替，然后生日用datetime或者其他时间类型也不太好，数据库中就存时间戳，然后程序中来格式化，所以类里面就有了属性和属性view这么一个东西...
> 
> 关于时间随便看了一篇文章：https://www.vertabelo.com/blog/what-datatype-should-you-use-to-represent-time-in-mysql-we-compare-datetime-timestamp-and-int/
> 不好说，还是要看做什么用，还有人的生日等。也许不是那么怪的网课😀

是的，时间类型的选择都各有各的说法，事实上，很多时候也由不得我们选择。在MySQL5.6.4之后以及jsr310后新加入的时间api，个人更加偏向datetime类型。不过话说回来，这个类在字段上的设计，也是没谁了...
